version: '3.8'
services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres_db
    environment:
      POSTGRES_DB: task_tracker
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5431:5431'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  task-tracker-api:
    build:
      context: ./task-tracker-api
    container_name: task_tracker_api
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/task_tracker
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  auth:
    build:
      context: ./auth
    container_name: auth_service
    ports:
      - '8081:8081'
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/task_tracker_auth
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  postgres_data:
